name: Linter

on: push

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.9.0
        with:
          clang-format-version: "13"
          style: "file"

  find-todos-fixme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run todo check
        run: | 
         if grep -rE -n 'TODO|FIXME' * | grep -v 'TODOLater'; then
          exit 1
         else
          echo "All good"
         fi

  find-missing-std:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run check for missing std
        run: |
          IDENTIFIERS="uint8_t uint16_t uint32_t uint64_t int8_t int16_t int32_t int64_t size_t"
          for identifier in $IDENTIFIERS; do
            if grep -rE -n "$identifier" | grep -v "std::$identifier"; then
              echo "[ERROR] found $identifier without std:: prefix"
              exit 1
            fi
          done
